### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by jackpotmonkey** [Phanx/BetterBattlePetTooltip#6] opened 2015-08-21 19:34 UTC
While browsing the AH
Edit 1:
Happened over the Cinder Pup pet, tooltip now missing for that pet and only that pet, other pets showing as normal.
Edit 2:
Hm, also affected the Lost Netherpup pet.

Date: 2015-08-21 11:32:49
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BetterBattlePetTooltip\Core.lua line 152:
   bad argument #1 to 'gsub' (string expected, got nil)
Debug:
   [C]: ?
   [C]: gsub()
   BetterBattlePetTooltip\Core.lua:152: GetOwnedBattlePetString()
   ..\FrameXML\BattlePetTooltip.lua:22:
      ..\FrameXML\BattlePetTooltip.lua:3
   [C]: ?
   [C]: BattlePetToolTip_Show()
   ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:1961: AuctionFrameItem_OnEnter()
   ...uc-Advanced\Modules\Auc-Util-CompactUI\CompactUI.lua:513:
      ...uc-Advanced\Modules\Auc-Util-CompactUI\CompactUI.lua:507
Locals:

AddOns:
  Swatter, v5.21e.5566 (SanctimoniousSwamprat)
  WowheadLooter, v60011
  Altoholic, vr164
  AraBrokerGuildFriends, vr72
  Atlas, v1.32.00
  AtlasCataclysm, v1.32.00
  AtlasDungeonLocs, v1.32.00
  AtlasMistsofPandaria, v1.32.00
  AtlasOutdoorRaids, v1.32.00
  AtlasTransportation, v1.32.00
  AtlasWorldEvents, v3.13
  AtlasWrathoftheLichKing, v1.32.00
  AtlasLoot, vv8.00.40
  AucAdvanced, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21e.5566.5459(5.21e/embedded)
  AucMatchUndercut, v5.21e.5566.5507(5.21e/embedded)
  AucStatSales, v5.21e.5566.5476(5.21e/embedded)
  AucStatWOWEcon, v5.21e.5566.5323(5.21e/embedded)
  AucUtilAHWindowControl, v5.21e.5566.5347(5.21e/embedded)
  AucUtilAppraiser, v5.21e.5566.5545(5.21e/embedded)
  AucUtilAskPrice, v5.21e.5566.5447(5.21e/embedded)
  AucUtilAutoMagic, v5.21e.5566.5537(5.21e/embedded)
  AucUtilCompactUI, v5.21e.5566.5550(5.21e/embedded)
  AucUtilEasyBuyout, v5.21e.5566.5507(5.21e/embedded)
  AucUtilItemSuggest, v5.21e.5566.5417(5.21e/embedded)
  AucUtilPriceLevel, v5.21e.5566.5535(5.21e/embedded)
  AucUtilScanButton, v5.21e.5566.5403(5.21e/embedded)
  AucUtilScanFinish, v5.21e.5566.5515(5.21e/embedded)
  AucUtilScanProgress, v5.21e.5566.4979(5.21e/embedded)
  AucUtilScanStart, v5.21e.5566.5347(5.21e/embedded)
  AucUtilSearchUI, v5.21e.5566.5556(5.21e/embedded)
  AucUtilSimpleAuction, v5.21e.5566.5531(5.21e/embedded)
  AucUtilVendMarkup, v5.21e.5566.4828(5.21e/embedded)
  Auctionator, v3.2.4
  Auditor2, v5.0.1
  Babylonian, v5.1.DEV.332(/embedded)
  Bagnon, v6.2.4
  BagnonConfig, v6.2.4
  BattlePetBreedID, vv1.4.5
  Bazooka, vv2.6.1
  BazookaOptions, vv2.6.1
  BetterBattlePetTooltip, v6.2.0.25
  BrokerAuditor, v5.0.1
  BrokerCurrency, v6.2.0.5
  BrokerLocation, v1.14
  cancelpetfight, vr46-release
  Configator, v5.1.DEV.382(/embedded)
  DataStore, vr55
  DataStoreAchievements, vr40
  DataStoreAgenda, vr22
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr35
  DataStoreContainers, vr51
  DataStoreCrafts, vr68
  DataStoreCurrencies, vr30
  DataStoreGarrisons, vr14
  DataStoreInventory, vr43
  DataStoreMails, vr43
  DataStorePets, vr38
  DataStoreQuests, vr35
  DataStoreReputations, vr36
  DataStoreSpells, vr26
  DataStoreStats, vr25
  DataStoreTalents, vr51
  DebugLib, v5.1.DEV.337(/embedded)
  EasyLunkerTurnIn, v1.12
  ElvUI, v8.23
  ElvUIEnhanced, v3.1.0-beta5
  ElvUIMicrobar, v1.77
  iLvLr, v2.3.102
  LibExtraTip, v5.12.DEV.390(/embedded)
  LibPeriodicTable31, vv3.3.0.493
  LibSharedMedia30, v3.0-93
  MacroToolkit, vv6.2.0.0
  PetJournalEnhanced, v2.9.16
  PetShoppingList, v1.0
  Postal, v3.5.4
  SavedInstances, v6.2.2
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  TradeSkillMaster, vv2.10.26
  TradeSkillMasterAccounting, vv2.4.5
  TradeSkillMasterAdditions, vv2.1.6
  TradeSkillMasterAppHelper, vv2.0.4
  TradeSkillMasterAuctionDB, vv2.7.1
  TradeSkillMasterAuctioning, vv2.4.6
  TradeSkillMasterCrafting, vv2.6.19
  TradeSkillMasterItemTracker, vv2.1.4
  TradeSkillMasterMailing, vv2.2.13
  TradeSkillMasterShopping, vv2.4.6
  TradeSkillMasterWoWuction, vv2.5.3
  zzInfoclock, v
  BlizRuntimeLib_enUS v6.2.0.60200 <none>
  (ck=c5f)

**Comment by Phanx** [comment] 2015-08-22 16:31
Duplicate of #5

**Closed by Phanx** 2015-08-22 16:31 UTC
